include: package:flutter_lints/flutter.yaml

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    use_key_in_widget_constructors: false 
    prefer_const_constructors_in_immutables: false
    implementation_imports: false
