name: cascading_menu_example
publish_to: none  

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  avocado_utils: ^0.1.0
  cascading_menu:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true