name: cascading_menu
description: A Flutter implementation of the cascading menu.
version: 0.1.0
repository: https://github.com/Oleksa5/cascading_menu

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  avocado_utils: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/icons/right_aligned_arrow_right.png
    - assets/icons/arrow_down.png